NAME: Xiao Yang,Zhengyuan Liu
EMAIL: avadayang@icloud.com,zhengyuanliu@ucla.edu


included files;
* lab3b.py: the Python source module for lab3b
* Makefile: a Makefile to build and run the deliverable program. The higher level targets are:
	* default ... produce an executable named lab3b by creating an script to interpret lab3b.py
	* dist ... create the deliverable tarball
	* clean ... delete all programs and output generated by the Makefile.
* README: a README text file containing descriptions of each of the included files and any other information about the submission


References:
The Second Extended File System, http://www.nongnu.org/ext2-doc/ext2.html