NAME: Zhengyuan Liu
EMAIL: zhengyuanliu@ucla.edu

README

Included Files:
* lab4b.c: C source files for an embedded application that builds and runs (with no errors or warnings) on an embedded system
* Makefile: build and test the application. The higher level targets include:
	* default ... build my program (compiling with the -Wall and -Wextra options).
	* check ... execute an automated smoke-test of the application to see if it runs and can talk to its sensors/actuators.
	* clean ... delete all programs and output generated by the Makefile
	* dist ... (runnable on a Linux desktop or server) create the deliverable tarball
* README: the README file containing a description of the included files.
* smoke_test.sh


Some Notes
* Because of Piazza post 381 (https://piazza.com/class/jdabtkwr46f7mn?cid=381), I log all the commands including invalid commands to the logfile, and I think it is reasonable because logfile should record all the input including error inputs.
* Based on the spec "... the computation associated with each operation is so small that you may find it much simpler to use a single thread (and polling or non-blocking I/O) to avoid hanging on standard input for commands that only rarely arrive." Therefore, I used a single thread to interact with the sensors and process the commands (using poll). The unit of the sleep time is one second, and every one second the main thread check the poll fd, if there are some commands then process the command, and if not, either go to sleep or report the temperature.


References:
* BeagleBone Tutorial: WiFi, SSH and SFTP
* BeagleBone Tutorial: GPIO, Interrupt, Analog and PWM
* mraa: libmraa - Low Level Skeleton Library for Communication on GNU/Linux platforms, https://iotdk.intel.com/docs/master/mraa/
* Grove - Temperature Sensor V1.2, http://wiki.seeedstudio.com/Grove-Temperature_Sensor_V1.2/
* strftime(3) - Linux man page, https://linux.die.net/man/3/strftime
* dprintf(3) - Linux man page, https://linux.die.net/man/3/dprintf
